### ISSUE TITLE
New Taiwan dollar TWD is missing

### ISSUE THREAD

**Issue by yourGuy** [gerardojbaez/money#9]

**Comment by ChrisToxz** [comment]
You should be able to add by your own in 'money/src/Currency.php'

`'USD' => [
            'code' => 'USD',
            'title' => 'US Dollar',
            'symbol' => '$',
            'precision' => 2,
            'thousandSeparator' => ',',
            'decimalSeparator' => '.',
            'symbolPlacement' => 'before'
        ],`

**Comment by gerardojbaez** [comment]
@ChrisToxz is right! Since you may already know the currency details, feel free to submit a PR and I'll make sure it gets added.
